<template>
  <div>
    <div class="table-box">
        <table align="left" border="1" cellpadding="1" cellspacing="1" style="width:500px;">
          <thead>
            <tr>
              <td colspan="3" style="text-align:center;vertical-align:middle;">
                <h2><strong>电话键</strong></h2>
              </td>
            </tr>
            <tr>
              <td>KEYCODE_CALL</td>
              <td>拨号键</td>
              <td>5</td>
            </tr>
            <tr>
              <td>KEYCODE_ENDCALL</td>
              <td>挂机键</td>
              <td>6</td>
            </tr>
            <tr>
              <td>KEYCODE_HOME</td>
              <td>按键Home</td>
              <td>3</td>
            </tr>
            <tr>
              <td>KEYCODE_MENU</td>
              <td>菜单键</td>
              <td>82</td>
            </tr>
            <tr>
              <td>KEYCODE_BACK</td>
              <td>返回键</td>
              <td>4</td>
            </tr>
            <tr>
              <td>KEYCODE_SEARCH</td>
              <td>搜索键</td>
              <td>84</td>
            </tr>
            <tr>
              <td>KEYCODE_CAMERA</td>
              <td>拍照键</td>
              <td>27</td>
            </tr>
            <tr>
              <td>KEYCODE_FOCUS</td>
              <td>拍照对焦键</td>
              <td>80</td>
            </tr>
            <tr>
              <td>KEYCODE_POWER</td>
              <td>电源键</td>
              <td>26</td>
            </tr>
            <tr>
              <td>KEYCODE_NOTIFICATION</td>
              <td>通知键</td>
              <td>83</td>
            </tr>
            <tr>
              <td>KEYCODE_MUTE</td>
              <td>话筒静音键</td>
              <td>91</td>
            </tr>
            <tr>
              <td>KEYCODE_VOLUME_MUTE</td>
              <td>扬声器静音键</td>
              <td>164</td>
            </tr>
            <tr>
              <td>KEYCODE_VOLUME_UP</td>
              <td>音量增加键</td>
              <td>24</td>
            </tr>
            <tr>
              <td>KEYCODE_VOLUME_DOWN</td>
              <td>音量减小键</td>
              <td>25</td>
            </tr>
            <tr>
              <th colspan="3" style="text-align:center;vertical-align:middle;">
                <h2>控制键</h2>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>KEYCODE_ENTER</td>
              <td>回车键</td>
              <td>66</td>
            </tr>
            <tr>
              <td>KEYCODE_ESCAPE</td>
              <td>ESC键</td>
              <td>111</td>
            </tr>
            <tr>
              <td>KEYCODE_DPAD_CENTER</td>
              <td>导航键 确定键</td>
              <td>23</td>
            </tr>
            <tr>
              <td>KEYCODE_DPAD_UP</td>
              <td>导航键 向上</td>
              <td>19</td>
            </tr>
            <tr>
              <td>KEYCODE_DPAD_DOWN</td>
              <td>导航键 向下</td>
              <td>20</td>
            </tr>
            <tr>
              <td>KEYCODE_DPAD_LEFT</td>
              <td>导航键 向左</td>
              <td>21</td>
            </tr>
            <tr>
              <td>KEYCODE_DPAD_RIGHT</td>
              <td>导航键 向右</td>
              <td>22</td>
            </tr>
            <tr>
              <td>KEYCODE_MOVE_HOME</td>
              <td>光标移动到开始键</td>
              <td>122</td>
            </tr>
            <tr>
              <td>KEYCODE_MOVE_END</td>
              <td>光标移动到末尾键</td>
              <td>123</td>
            </tr>
            <tr>
              <td>KEYCODE_PAGE_UP</td>
              <td>向上翻页键</td>
              <td>92</td>
            </tr>
            <tr>
              <td>KEYCODE_PAGE_DOWN</td>
              <td>向下翻页键</td>
              <td>93</td>
            </tr>
            <tr>
              <td>KEYCODE_DEL</td>
              <td>退格键</td>
              <td>67</td>
            </tr>
            <tr>
              <td>KEYCODE_FORWARD_DEL</td>
              <td>删除键</td>
              <td>112</td>
            </tr>
            <tr>
              <td>KEYCODE_INSERT</td>
              <td>插入键</td>
              <td>124</td>
            </tr>
            <tr>
              <td>KEYCODE_TAB</td>
              <td>Tab键</td>
              <td>61</td>
            </tr>
            <tr>
              <td>KEYCODE_NUM_LOCK</td>
              <td>小键盘锁</td>
              <td>143</td>
            </tr>
            <tr>
              <td>KEYCODE_CAPS_LOCK</td>
              <td>大写锁定键</td>
              <td>115</td>
            </tr>
            <tr>
              <td>KEYCODE_BREAK</td>
              <td>Break/Pause键</td>
              <td>121</td>
            </tr>
            <tr>
              <td>KEYCODE_SCROLL_LOCK</td>
              <td>滚动锁定键</td>
              <td>116</td>
            </tr>
            <tr>
              <td>KEYCODE_ZOOM_IN</td>
              <td>放大键</td>
              <td>168</td>
            </tr>
            <tr>
              <td>KEYCODE_ZOOM_OUT</td>
              <td>缩小键</td>
              <td>169</td>
            </tr>
            <tr>
              <td colspan="3" style="text-align:center;vertical-align:middle;">
                <h2>组合键</h2>
              </td>
            </tr>
            <tr>
              <td>KEYCODE_ALT_LEFT</td>
              <td colspan="2" rowspan="1">Alt+Left</td>
            </tr>
            <tr>
              <td>KEYCODE_ALT_RIGHT</td>
              <td colspan="2" rowspan="1">Alt+Right</td>
            </tr>
            <tr>
              <td>KEYCODE_CTRL_LEFT</td>
              <td colspan="2" rowspan="1">Control+Left</td>
            </tr>
            <tr>
              <td>KEYCODE_CTRL_RIGHT</td>
              <td colspan="2" rowspan="1">Control+Right</td>
            </tr>
            <tr>
              <td>KEYCODE_SHIFT_LEFT</td>
              <td colspan="2" rowspan="1">Shift+Left</td>
            </tr>
            <tr>
              <td>KEYCODE_SHIFT_RIGHT</td>
              <td colspan="2" rowspan="1">Shift+Right</td>
            </tr>
            <tr>
              <td colspan="3" style="text-align:center;">
                <h2>按键</h2>
              </td>
            </tr>
            <tr>
              <td>KEYCODE_0</td>
              <td>按键'0'</td>
              <td>7</td>
            </tr>
            <tr>
              <td>KEYCODE_1</td>
              <td>按键'1'</td>
              <td>8</td>
            </tr>
            <tr>
              <td>KEYCODE_2</td>
              <td>按键'2'</td>
              <td>9</td>
            </tr>
            <tr>
              <td>KEYCODE_3</td>
              <td>按键'3'</td>
              <td>10</td>
            </tr>
            <tr>
              <td>KEYCODE_4</td>
              <td>按键'4'</td>
              <td>11</td>
            </tr>
            <tr>
              <td>KEYCODE_5</td>
              <td>按键'5'</td>
              <td>12</td>
            </tr>
            <tr>
              <td>KEYCODE_6</td>
              <td>按键'6'</td>
              <td>13</td>
            </tr>
            <tr>
              <td>KEYCODE_7</td>
              <td>按键'7'</td>
              <td>14</td>
            </tr>
            <tr>
              <td>KEYCODE_8</td>
              <td>按键'8'</td>
              <td>15</td>
            </tr>
            <tr>
              <td>KEYCODE_9</td>
              <td>按键'9'</td>
              <td>16</td>
            </tr>
            <tr>
              <td>KEYCODE_A</td>
              <td>按键'A'</td>
              <td>29</td>
            </tr>
            <tr>
              <td>KEYCODE_B</td>
              <td>按键'B'</td>
              <td>30</td>
            </tr>
            <tr>
              <td>KEYCODE_C</td>
              <td>按键'C'</td>
              <td>31</td>
            </tr>
            <tr>
              <td>KEYCODE_D</td>
              <td>按键'D'</td>
              <td>32</td>
            </tr>
            <tr>
              <td>KEYCODE_E</td>
              <td>按键'E'</td>
              <td>33</td>
            </tr>
            <tr>
              <td>KEYCODE_F</td>
              <td>按键'F'</td>
              <td>34</td>
            </tr>
            <tr>
              <td>KEYCODE_G</td>
              <td>按键'G'</td>
              <td>35</td>
            </tr>
            <tr>
              <td>KEYCODE_H</td>
              <td>按键'H'</td>
              <td>36</td>
            </tr>
            <tr>
              <td>KEYCODE_I</td>
              <td>按键'I'</td>
              <td>37</td>
            </tr>
            <tr>
              <td>KEYCODE_J</td>
              <td>按键'J'</td>
              <td>38</td>
            </tr>
            <tr>
              <td>KEYCODE_K</td>
              <td>按键'K'</td>
              <td>39</td>
            </tr>
            <tr>
              <td>KEYCODE_L</td>
              <td>按键'L'</td>
              <td>40</td>
            </tr>
            <tr>
              <td>KEYCODE_M</td>
              <td>按键'M'</td>
              <td>41</td>
            </tr>
            <tr>
              <td>KEYCODE_N</td>
              <td>按键'N'</td>
              <td>42</td>
            </tr>
            <tr>
              <td>KEYCODE_O</td>
              <td>按键'O'</td>
              <td>43</td>
            </tr>
            <tr>
              <td>KEYCODE_P</td>
              <td>按键'P'</td>
              <td>44</td>
            </tr>
            <tr>
              <td>KEYCODE_Q</td>
              <td>按键'Q'</td>
              <td>45</td>
            </tr>
            <tr>
              <td>KEYCODE_R</td>
              <td>按键'R'</td>
              <td>46</td>
            </tr>
            <tr>
              <td>KEYCODE_S</td>
              <td>按键'S'</td>
              <td>47</td>
            </tr>
            <tr>
              <td>KEYCODE_T</td>
              <td>按键'T'</td>
              <td>48</td>
            </tr>
            <tr>
              <td>KEYCODE_U</td>
              <td>按键'U'</td>
              <td>49</td>
            </tr>
            <tr>
              <td>KEYCODE_V</td>
              <td>按键'V'</td>
              <td>50</td>
            </tr>
            <tr>
              <td>KEYCODE_W</td>
              <td>按键'W'</td>
              <td>51</td>
            </tr>
            <tr>
              <td>KEYCODE_X</td>
              <td>按键'X'</td>
              <td>52</td>
            </tr>
            <tr>
              <td>KEYCODE_Y</td>
              <td>按键'Y'</td>
              <td>53</td>
            </tr>
            <tr>
              <td>KEYCODE_Z</td>
              <td>按键'Z'</td>
              <td>54</td>
            </tr>
            <tr>
              <td colspan="2" rowspan="1" style="text-align:center;">
                <h2>多媒体键</h2>
              </td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_PLAY</td>
              <td>多媒体键 播放</td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_STOP</td>
              <td>多媒体键 停止</td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_PAUSE</td>
              <td>多媒体键 暂停</td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_PLAY_PAUSE</td>
              <td>多媒体键 播放/暂停</td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_FAST_FORWARD</td>
              <td>多媒体键 快进</td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_REWIND</td>
              <td>多媒体键 快退</td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_NEXT</td>
              <td>多媒体键 下一首</td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_PREVIOUS</td>
              <td>多媒体键 上一首</td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_CLOSE</td>
              <td>多媒体键 关闭</td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_EJECT</td>
              <td>多媒体键 弹出</td>
            </tr>
            <tr>
              <td>KEYCODE_MEDIA_RECORD</td>
              <td>多媒体键 录音</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td>KEYCODE_F1</td>
              <td>按键F1</td>
            </tr>
            <tr>
              <td>KEYCODE_F2</td>
              <td>按键F2</td>
            </tr>
            <tr>
              <td>KEYCODE_F3</td>
              <td>按键F3</td>
            </tr>
            <tr>
              <td>KEYCODE_F4</td>
              <td>按键F4</td>
            </tr>
            <tr>
              <td>KEYCODE_F5</td>
              <td>按键F5</td>
            </tr>
            <tr>
              <td>KEYCODE_F6</td>
              <td>按键F6</td>
            </tr>
            <tr>
              <td>KEYCODE_F7</td>
              <td>按键F7</td>
            </tr>
            <tr>
              <td>KEYCODE_F8</td>
              <td>按键F8</td>
            </tr>
            <tr>
              <td>KEYCODE_F9</td>
              <td>按键F9</td>
            </tr>
            <tr>
              <td>KEYCODE_F10</td>
              <td>按键F10</td>
            </tr>
            <tr>
              <td>KEYCODE_F11</td>
              <td>按键F11</td>
            </tr>
            <tr>
              <td>KEYCODE_F12</td>
              <td>按键F12</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td>KEYCODE_PLUS</td>
              <td>按键'+'</td>
            </tr>
            <tr>
              <td>KEYCODE_MINUS</td>
              <td>按键'-'</td>
            </tr>
            <tr>
              <td>KEYCODE_STAR</td>
              <td>按键'*'</td>
            </tr>
            <tr>
              <td>KEYCODE_SLASH</td>
              <td>按键'/'</td>
            </tr>
            <tr>
              <td>KEYCODE_EQUALS</td>
              <td>按键'='</td>
            </tr>
            <tr>
              <td>KEYCODE_AT</td>
              <td>按键'@'</td>
            </tr>
            <tr>
              <td>KEYCODE_POUND</td>
              <td>按键'#'</td>
            </tr>
            <tr>
              <td>KEYCODE_APOSTROPHE</td>
              <td>按键''' (单引号)</td>
            </tr>
            <tr>
              <td>KEYCODE_BACKSLASH</td>
              <td>按键'\'</td>
            </tr>
            <tr>
              <td>KEYCODE_COMMA</td>
              <td>按键','</td>
            </tr>
            <tr>
              <td>KEYCODE_PERIOD</td>
              <td>按键'.'</td>
            </tr>
            <tr>
              <td>KEYCODE_LEFT_BRACKET</td>
              <td>按键'['</td>
            </tr>
            <tr>
              <td>KEYCODE_RIGHT_BRACKET</td>
              <td>按键']'</td>
            </tr>
            <tr>
              <td>KEYCODE_SEMICOLON</td>
              <td>按键';'</td>
            </tr>
            <tr>
              <td>KEYCODE_GRAVE</td>
              <td>按键'`'</td>
            </tr>
            <tr>
              <td>KEYCODE_SPACE</td>
              <td>空格键</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_0</td>
              <td>小键盘按键'0'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_1</td>
              <td>小键盘按键'1'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_2</td>
              <td>小键盘按键'2'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_3</td>
              <td>小键盘按键'3'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_4</td>
              <td>小键盘按键'4'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_5</td>
              <td>小键盘按键'5'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_6</td>
              <td>小键盘按键'6'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_7</td>
              <td>小键盘按键'7'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_8</td>
              <td>小键盘按键'8'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_9</td>
              <td>小键盘按键'9'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_ADD</td>
              <td>小键盘按键'+'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_SUBTRACT</td>
              <td>小键盘按键'-'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_MULTIPLY</td>
              <td>小键盘按键'*'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_DIVIDE</td>
              <td>小键盘按键'/'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_EQUALS</td>
              <td>小键盘按键'='</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_COMMA</td>
              <td>小键盘按键','</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_DOT</td>
              <td>小键盘按键'.'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_LEFT_PAREN</td>
              <td>小键盘按键'('</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_RIGHT_PAREN</td>
              <td>小键盘按键')'</td>
            </tr>
            <tr>
              <td>KEYCODE_NUMPAD_ENTER</td>
              <td>小键盘按键回车</td>
            </tr>
          </tbody>
        </table>
      </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
    };
  },

  props: {},

  components: {},

  computed: {},

  mounted:function() {},

  methods: {}
}

</script>
<style lang='scss' scoped>
</style>